
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@aspect_rules_lint//format:defs.bzl", "format_test")

format_test(
    name = "format_test",
    cc = "//:clang_format_hermetic",
    srcs = glob(["*.cpp", "*.h"]),
)

cc_library(
    name = "interpreter",
    srcs = ["interpreter.cpp"],
    hdrs = ["interpreter.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core:json_utils",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@nlohmann_json//:json",
        "@quickjs-ng//:quickjs",
    ],
)

cc_test(
    name = "interpreter_test",
    srcs = ["interpreter_test.cpp"],
    deps = [
        ":interpreter",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "run_js_fuzz_test",
    srcs = ["run_js_fuzz_test.cpp"],
    copts = [
        "-Wno-unused-parameter",
        "-Wno-deprecated-declarations",
    ],
    deps = [
        ":interpreter",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@fuzztest//fuzztest",
        "@fuzztest//fuzztest:fuzztest_gtest_main",
        "@googletest//:gtest",
        "@nlohmann_json//:json",
    ],
)