load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "protocol",
    hdrs = [
        "protocol.h",
        "types.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/time",
        "@nlohmann_json//:json",
    ],
)

cc_library(
    name = "json_rpc",
    srcs = ["json_rpc.cpp"],
    hdrs = ["json_rpc.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":protocol",
        "//core:json_utils",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@nlohmann_json//:json",
    ],
)

cc_test(
    name = "json_rpc_test",
    srcs = ["json_rpc_test.cpp"],
    deps = [
        ":json_rpc",
        "//core:json_utils",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
        "@nlohmann_json//:json",
    ],
)

