#include "interface/command_definitions.h"
namespace slop {
const std::vector<CommandDefinition>& GetCommandDefinitions() {
  static const std::vector<CommandDefinition> kDefinitions = {
      {"/help", {}, {}, {"Show this help message"}, "Core Operations"},
      {"/exit", {}, {"/quit"}, {"Exit the program"}, "Core Operations"},
      {"/edit", {}, {}, {"Open last input in EDITOR"}, "Core Operations"},
      {"/exec", {}, {}, {"/exec <command>        Execute shell command"}, "Core Operations"},
      {"/stats", {}, {"/usage"}, {"Show session usage statistics"}, "Core Operations"},
      {"/session",
       {"list", "switch", "rollback", "remove", "clear", "clone"},
       {},
       {"/session list", "/session switch <name> [group]", "/session rollback <group>",
        "/session remove <name>", "/session clear", "/session clone <name>"},
       "Session & Memory"},
      {"/agents_md",
       {"show", "reload"},
       {"/memo"},
       {"/agents_md show", "/agents_md reload [path]"},
       "Session & Memory"},
      {"/message",
       {"list", "show", "remove"},
       {"/messages"},
       {"/message list [N]", "/message show <GID>", "/message remove <GID>"},
       "Context & History"},
      {"/undo", {}, {}, {"Remove last message"}, "Context & History"},
      {"/context",
       {"show"},
       {},
       {"/context <retain_groups> [watermark_tokens]", "/context show"},
       "Context & History"},
      {"/review",
       {"session", "mail", "mail approve", "git"},
       {},
       {"/review session", "/review mail", "/review mail approve", "/review git <ref>"},
       "Context & History"},
      {"/feedback", {}, {}, {"/feedback"}, "Context & History"},
      {"/model", {}, {}, {"/model <name>"}, "Model & Configuration"},
      {"/models", {}, {}, {"/models [filter]"}, "Model & Configuration"},
      {"/throttle", {}, {}, {"/throttle [N]"}, "Model & Configuration"},
      {"/schema", {}, {}, {"Show schema"}, "Model & Configuration"},
      {"/mode", {"mail", "standard"}, {}, {"/mode [mail|standard] [branchname]"}, "Model & Configuration"},
      {"/tool",
       {"list", "show", "js_help"},
       {"/tools"},
       {"/tool list", "/tool show <name>", "/tool js_help"},
       "Agent Capabilities"},
      {"/skill",
       {"list", "activate", "deactivate", "add", "edit", "delete"},
       {},
       {"/skill list", "/skill activate <ID>", "/skill deactivate <ID>", "/skill add", "/skill edit <ID>",
        "/skill delete <ID>", "hey <skill> <query>"},
       "Agent Capabilities"},
      {"/scratchpad",
       {"edit", "save"},
       {},
       {"/scratchpad edit", "/scratchpad save"},
       "Context & History"},
  };
  return kDefinitions;
}
}  // namespace slop
