#!/bin/bash
set -euo pipefail

# Navigate to workspace root
if [ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]; then
  cd "$BUILD_WORKSPACE_DIRECTORY"
else
  cd "$(dirname "$0")/.."
fi

echo "=== Generating clang-tidy fixes ==="
# Use a separate output base for linting to avoid discarding the analysis cache of the main build.
# This makes switching between building and fixing much faster and avoids the "discarding analysis cache" warning.
MAIN_OUTPUT_BASE=$(bazel info output_base)
LINT_OUTPUT_BASE="${MAIN_OUTPUT_BASE}-lint"

# Run the aspect with the fix flag enabled.
# We use output_groups=rules_lint_patch to get the patch files.
# Note: This build might fail if there are compilation errors, 
# but it should still produce patches for lint errors it finds before failing.
bazel --output_base="$LINT_OUTPUT_BASE" build //... \
    --aspects=//:linters.bzl%clang_tidy \
    --output_groups=rules_lint_patch \
    --@aspect_rules_lint//lint:fix || echo "Bazel build finished with some issues (possibly lint fixes found)."

echo "=== Applying fixes ==="
# Find all non-empty patch files generated by the aspect
# We need to look into the separate lint output base.
LINT_BIN_DIR=$(bazel --output_base="$LINT_OUTPUT_BASE" info bazel-bin)
PATCHES=$(find -L "$LINT_BIN_DIR" -name "*.AspectRulesLintClangTidy.patch" -size +0 2>/dev/null || true)

if [ -z "$PATCHES" ]; then
    echo "No clang-tidy fixes to apply."
else
    for patch in $PATCHES; do
        echo "Applying patch: $patch"
        patch -p1 < "$patch"
    done
    echo "Successfully applied clang-tidy fixes."
fi
