#!/bin/bash
set -euo pipefail

# Navigate to workspace root
if [ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]; then
  cd "$BUILD_WORKSPACE_DIRECTORY"
else
  cd "$(dirname "$0")/.."
fi

echo "=== Generating clang-tidy fixes ==="
# Run the aspect with the fix flag enabled.
# We use output_groups=rules_lint_patch to get the patch files.
# Note: This build might fail if there are compilation errors, 
# but it should still produce patches for lint errors it finds before failing.
bazel build //... \
    --aspects=//:linters.bzl%clang_tidy \
    --output_groups=rules_lint_patch \
    --@aspect_rules_lint//lint:fix || echo "Bazel build finished with some issues (possibly lint fixes found)."

echo "=== Applying fixes ==="
# Find all non-empty patch files generated by the aspect
# Using -L to follow symlinks in bazel-bin
PATCHES=$(find -L bazel-bin -name "*.AspectRulesLintClangTidy.patch" -size +0 2>/dev/null || true)

if [ -z "$PATCHES" ]; then
    echo "No clang-tidy fixes to apply."
else
    for patch in $PATCHES; do
        echo "Applying patch: $patch"
        patch -p1 < "$patch"
    done
    echo "Successfully applied clang-tidy fixes."
fi
